services:
  cisco-gui:
    build: .
    container_name: cisco-gui
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    volumes:
      - ./database.sqlite:/app/database.sqlite
